server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-connections: 20000
    accept-count: 1000
    threads:
      max: 1000
      min-spare: 30

spring:
  application:
    name: demo
  messages:
    basename: i18n/messages
  aop:
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization.write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 6400
      properties:
        interceptor:
          classes: io.github.changebooks.kafka.LogProducerInterceptor
        linger:
          ms: 1000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: demo
      client-id: demo
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 500
      properties:
        interceptor:
          classes: io.github.changebooks.kafka.LogConsumerInterceptor
    listener:
      ack-mode: manual
      type: batch
